services:

  db-proxy:
    image: ginuerzh/gost:latest
    container_name: db-proxy-server
    # Escuta na interface VPN e encaminha para o banco externo
    command: >
      -L=tcp://:5432/${DB_HOST}:${DB_PORT}
    restart: unless-stopped
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    # Não expõe portas externamente - só via VPN
    # ports: []
    networks:
      - vpnservernet

  ts-server:
    image: tailscale/tailscale:latest
    container_name: ts-server
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=${TS_USERSPACE:-true}  # userspace mode evita /dev/net/tun em LXC/Proxmox
      # Use TS_HOSTNAME para nomear o nó no Tailscale (não use "hostname" com network_mode)
      - TS_HOSTNAME=${TS_HOSTNAME:-vpn-db-server}
      - TS_EXTRA_ARGS=--advertise-routes=${ADVERTISE_ROUTES}
    volumes:
      - ./ts-server/state:/var/lib/tailscale
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    # Conecta à rede dedicada do projeto
    networks:
      - vpnservernet

networks:
  vpnservernet:
    driver: bridge
    depends_on:
      - db-proxy
